import type { Metadata } from "next";
import "./globals.css";
import { NavigationDock } from "@/components/navigation-dock"
import { Albert_Sans } from "next/font/google"
import { Pill } from "@/components/ui/pill"
import { Background } from "@/components/background"
import { LenisProvider } from "@/components/lenis-provider"

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
})




export const metadata: Metadata = {
  title: "Leon Ekelund Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${albertSans.variable}`}>
        <LenisProvider>
          <Background />
          <a href="mailto:leongudmundssonekelund@gmail.com" className="fixed top-4 right-4 z-50">
            <Pill>Get in touch</Pill>
          </a>
          {children}
          <NavigationDock />
        </LenisProvider>
      </body>
    </html>
  );
}
